#!/usr/bin/env bash
#Double the number of webservers

get_subdomain_info() {
    domain=$1
    subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        echo "$(dig $sub.$domain | awk '/ANSWER SECTION:/ {getline; print "The subdomain '"$sub"' is a "$4" record and points to "$5}')"
    done
}

get_subdomain_info "$@"
