#!/usr/bin/env bash
#transfer file from client to server

path=$1
ip=$2
username=$3
keyfile=$4

if [ "$#" -lt 3 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

export SSH_OPTIONS="-o StrictHostKeyChecking=no"

scp $SSH_OPTIONS -i $keyfile $path $username@$ip:~/
