#!/usr/bin/env bash
#redirection

sudo apt-get -y update
sudo apt -y upgrade
sudo apt-get -y install nginx

path=/var/www/html/index.html
secpath=/etc/nginx/sites-available/default
sudo bash -c "echo 'Hello World!' > $path"
service nginx start

phrase="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n} \n"

sudo sed -i "30i $phrase" $secfile

sudo service nginx restart