#!/usr/bin/env bash

# This script is used to add custom HTTP response headers to the HTTP response

sudo apt-get -y update
sudo apt-get -y insall nginx
file_path=var/www/html/index.html
file_path2=etc/nginx/sites-available/default
sudo bash -c "echo 'Hello World' > $file_path"

sudo service nginx start
phrase="location /redirect_me {\nreturn 301 https://www.google.com;\n}\n}"
sudo sed -i "30i $phrase" $file_path2

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
phrase2="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n\t\t# hello i am ayoub \n\t\n}\n"
sudo sed -i "30i $phrase2" $file1

sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" $file1
sudo service nginx restart