#!/usr/bin/env bash
#install and configure load_balancer

sudo apt-get -y update
apt-get install -y haproxy

frontend http-in 
  bind *:80
  mode http
  default_backend web_server
backend web_server
  mode http
  balance roudrobin
  option httpchk HEAD /
HTTP/1.0\r\nHost:localhost
  server web-01 54.237.94.232:80 check
  server web-02 54.162.5.215:80 check

EOF
sudo systemctl restart haproxy
