#!/usr/bin/env bash
# install and configure load_balancer

sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i "9i ENABLED=1" /etc/default/haproxy
sudo cat >> /etc/haproxy/haproxy.cfg <<EOF
frontend http-in
  bind *:80
  mode http
  default_backend web_server

backend web_server
  mode http
  balance roundrobin
  server 432577-web-01 52.4.51.54:80 check
  server 432577-web-02 100.26.20.115:80 check
EOF

sudo service haproxy restart
