#!/usr/bin/env bash
# install and configure load_balancer

sudo apt-get -y update
sudo apt-get install -y haproxy

cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend http-in
  bind *:80
  mode http
  default_backend web_server

backend web_server
  mode http
  balance roundrobin
  option httpchk HEAD / HTTP/1.0\r\nHost:localhost
  server web-01 54.237.94.232:80 check
  server web-02 54.162.5.215:80 check
EOF

sudo systemctl restart haproxy
