#!/usr/bin/env bash
# Check if an argument is provided

if [ $# -eq 0 ]; then
echo "Usage: $0 {IP_ADRESS}"
exit 1
fi

ip_address=$1
echo "Pinging $ip_address 5 times..."
ping -c 5 $ip_address
exit $?
