#!/usr/bin/env bash
#line 4 bad luck line 8 good luck otherwise Best school
i=0
while [ $i -le 9 ] 
do
    i=$((i+1))
if [[ $i -eq 4 ]]
then
    echo "bad luck"
elif [[ $i -eq 8 ]]
then
    echo "good luck"
else
    echo "Best School"
fi
done