#!/usr/bin/env bash
#Alternates between displaying bad luck on the 4th loop,
#good luck on the 8th loop, and Best School for other iterations.
i=0
while [ $i -le 9 ] 
do
    i=$((i+1))
if [[ $i -eq 4 ]]
then
    echo "Bad luck"
elif [[ $i -eq 8 ]]
then
    echo "good luck"
else
    echo "Best School"
fi
done