#!/usr/bin/env bash
#check the file
file="school"
if [ -e "$file" ]; then
    echo "$file file exists"
    if [ -s "$file" ]; then
        echo "$file file is not empty"
    else
        echo "$file is aregular file"
    fi
    if [ -f "file" ]; then
    echo "$file is aregular file"
    fi
    else
        echo "$file file does not exist"
    fi