#!/usr/bin/env bash
# Run nginx as nginx user

sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

sudo sed -i 's/80  default_server/8080 default_server/' /etc/nginx/sites-enavliabled/default

pkill apache2

sudo -u service nginx restart
