#!/usr/bin/env bash
# who ami
CONFIG_PATH="/path/to/custom_nginx.conf"

# Run the Docker container with the custom configuration
docker run -d \
    --name nginx-container \
    -p 8080:8080 \
    -v $CONFIG_PATH:/etc/nginx/conf.d/default.conf \
    $IMAGE_NAME
